sonar.projectKey=FarahBenFradj_mon-projet-ci
sonar.projectName=Mon Projet React Node
sonar.organization=mon-projet-react-node
sonar.host.url=https://sonarcloud.io

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8