sonar.projectKey=4fc6e9d99733f83ddbd1aed455fba041a6bd0a17
sonar.projectName=Mon Projet React Node
sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8